##' Post Rest Call
##' 
##' @param url The url specifying where the data should be uploaded.  Usually
##' this is generated by some other function, as it tends to contain
##' information such as the token.
##' @param data An object containing the data in json format.  Again, this is
##' usually produced by a function rather than directly supplied by the user.
##' @param nullValue Value that should be used for missing values. See
##'   \link{fromJSON} in RJSONIO for details.
##' 
##' @return The response from the server.
##' 

PostRestCall <- function(url, data, nullValue = NULL) {
  
  ch <- RCurl::getCurlHandle()
  
  withCallingHandlers(if (Sys.info()['sysname'] == 'Darwin') { 
    response <- RCurl::getURL(
      url = url,
      curl = ch,
      verbose = FALSE,
      noproxy = .swsenv$swsContext.noProxy,
      ssl.verifypeer = FALSE, 
      sslcert = path.expand(.swsenv$swsContext.clientP12),
      sslcertpasswd = .swsenv$swsContext.p12Password,
      ssl.verifyhost = 2,
      httpheader = c(Accept = "application/json", 'Content-Type' = "application/json"),
      post = 1,
      postfields = RJSONIO::toJSON(data, digits = 30),
      .encoding = "UTF-8")
  } else {
    response <- RCurl::getURL(
      url = url,
      curl = ch,
      verbose = FALSE,
      noproxy = .swsenv$swsContext.noProxy,
      ssl.verifypeer = FALSE, 
      sslcert = path.expand(.swsenv$swsContext.clientCertificate),
      sslkey = path.expand(.swsenv$swsContext.clientKey),
      ssl.verifyhost = 2,
      httpheader = c(Accept = "application/json", 'Content-Type' = "application/json"),
      post = 1,
      postfields = RJSONIO::toJSON(data, digits = 30),
      .encoding = "UTF-8")
  },
  SSL_CONNECT_ERROR = function(e){
    stop("Incorrect certificates. Either use 'SetClientFiles' or put the correct certificates in ", 
         dirname(.swsenv$swsContext.clientCertificate), call. = FALSE)
  })
  
  # Check returned status code.
  #
  status <- RCurl::getCurlInfo(ch, which = "response.code")
  if(status != 200) {
    HandleHTTPError(status, response)
  }
  
  # Prevent error on blank response
  if(response == ""){
    return(invisible(""))
  } else {
    return(RJSONIO::fromJSON(response, nullValue = nullValue))
  }
  
}
