##' Put Rest Call
##' 
##' @param url The url specifying where the data should be uploaded.  Usually
##' this is generated by some other function, as it tends to contain
##' information such as the token.
##' @param data An object containing the data in json format.  Again, this is
##' usually produced by a function rather than directly supplied by the user.
##' 
##' @return The response from the server.
##' 

PutRestCall <- function(url, data) {

	ch <- RCurl::getCurlHandle()
	response <- RCurl::httpPUT(
		url = url,
		curl = ch,
		verbose = FALSE,
		noproxy = swsContext.noProxy,
		ssl.verifypeer = FALSE, 
		sslcert = path.expand(swsContext.clientCertificate),
		sslkey = path.expand(swsContext.clientKey),
		#cacert = path.expand(swsContext.serverCertificate),
		ssl.verifyhost = 2,
		httpheader = c(Accept = "application/json", 'Content-Type' = "application/json", Expect = ""),
		content = RJSONIO::toJSON(data, digits = 30))

	# Check returned status code.
	#
	status <- RCurl::getCurlInfo(ch, which = "response.code")
	if(status != 200) {
		stop(paste("Unable to perform REST call to SWS server. Status code was", status))
	}

	RJSONIO::fromJSON(response)
}
