##' Put Rest Call
##' 
##' @param url The url specifying where the data should be uploaded.  Usually
##' this is generated by some other function, as it tends to contain
##' information such as the token.
##' @param data An object containing the data in json format.  Again, this is
##' usually produced by a function rather than directly supplied by the user.
##' 
##' @return The response from the server.
##' 

PutRestCall <- function(url, data) {

	ch <- RCurl::getCurlHandle()
  if (Sys.info()['sysname'] == 'Darwin') { 
    response <- RCurl::httpPUT(
      url = url,
      curl = ch,
      verbose = FALSE,
      noproxy = .swsenv$swsContext.noProxy,
      ssl.verifypeer = FALSE, 
      sslcert = path.expand(.swsenv$swsContext.clientP12),
      sslcertpasswd = .swsenv$swsContext.p12Password,
      ssl.verifyhost = 2,
      httpheader = c(Accept = "application/json", 'Content-Type' = "application/json", Expect = ""),
      content = RJSONIO::toJSON(data, digits = 30))
  } else {
    response <- RCurl::httpPUT(
      url = url,
      curl = ch,
      verbose = FALSE,
      noproxy = .swsenv$swsContext.noProxy,
      ssl.verifypeer = FALSE, 
      sslcert = path.expand(.swsenv$swsContext.clientCertificate),
      sslkey = path.expand(.swsenv$swsContext.clientKey),
      ssl.verifyhost = 2,
      httpheader = c(Accept = "application/json", 'Content-Type' = "application/json", Expect = ""),
      content = RJSONIO::toJSON(data, digits = 30))
  }

	# Check returned status code.
	#
	status <- RCurl::getCurlInfo(ch, which = "response.code")
	if(status != 200) {
		HandleHTTPError(status, response)
	}

	RJSONIO::fromJSON(response)
}
