##' Put Rest Call
##'
##' @param url The url specifying where the data should be uploaded.  Usually
##' this is generated by some other function, as it tends to contain
##' information such as the token.
##' @param data An object containing the data in json format.  Again, this is
##' usually produced by a function rather than directly supplied by the user.
##' @param nullValue Value that should be used for missing values. See
##'   \link{fromJSON} in RJSONIO for details.
##'
##' @return The response from the server.
##'
##' @keywords internal

PutRestCall <- function(url, data, nullValue = NULL) {
  
  # TODO check .encoding = "UTF-8" parameter that was passed to RCurl::getURL()

  ch <- curl::new_handle()
  curl::handle_setheaders(ch,
    .list = list(Accept = "application/json", `Content-Type` = "application/json"))
  
  withCallingHandlers({
    if (Sys.info()['sysname'] == 'Darwin') {
      curl::handle_setopt(ch,
                          verbose = FALSE,
                          noproxy = .swsenv$swsContext.noProxy,
                          ssl_verifypeer = FALSE,
                          sslcert = path.expand(.swsenv$swsContext.clientP12),
                          sslcertpasswd = .swsenv$swsContext.p12Password,
                          ssl_verifyhost = 2,
                          customrequest = "PUT",
                          postfields = RJSONIO::toJSON(data, digits = 30))
    } else {
      curl::handle_setopt(ch,
                          verbose = FALSE,
                          noproxy = .swsenv$swsContext.noProxy,
                          ssl_verifypeer = FALSE,
                          sslcert = path.expand(.swsenv$swsContext.clientCertificate),
                          sslkey = path.expand(.swsenv$swsContext.clientKey),
                          ssl_verifyhost = 2,
                          customrequest = "PUT",
                          postfields = RJSONIO::toJSON(data, digits = 30))
    }
    response <- curl_fetch_memory(url, handle = ch)
  },
  SSL_CONNECT_ERROR = function(e){
    stop("Incorrect certificates. Either use 'SetClientFiles' or put the correct certificates in ", 
         dirname(.swsenv$swsContext.clientCertificate), call. = FALSE)
  },
  # TODO replace `RCurl` call with something from `curl`
  HTTPError = function(e){
    #status <- RCurl::getCurlInfo(ch, which = "response.code")
    stop(paste0("Unable to perform REST call to SWS server\nHTTP status: ", #status, 
                "\n", e$message), call. = FALSE)
  })
  
  # Check returned status code.
  #
	status <- response$status_code
  content <- rawToChar(response$content)

  if (status != 200) {
    HandleHTTPError(status, content)
  }
  
  # Prevent error on blank content
  if (content == "") {
    return(invisible(""))
  } else {
    return(RJSONIO::fromJSON(content, nullValue = nullValue))
  }
  
}
